SecRuleEngine On 
SecRequestBodyAccess On

SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject

SecAuditEngine RelevantOnly
SecAuditLog /var/log/caddy/coraza-audit.log
SecAuditLogParts ABCFHKZ
SecAuditLogFormat JSON
SecDebugLog /var/log/caddy/coraza-debug.log
SecDebugLogLevel 9
