import { isIP } from "node:net";

function normalizeList(values, name) {
  if (!Array.isArray(values) || values.length > 128) throw new Error(`${name} must contain at most 128 IPs/CIDRs`);
  return [...new Set(values.map((value) => {
    const entry = String(value).trim();
    const [address, bits, extra] = entry.split("/");
    const family = isIP(address);
    if (!family || extra !== undefined || (bits !== undefined && (!/^\d{1,3}$/.test(bits) || Number(bits) > (family === 4 ? 32 : 128)))) {
      throw new Error(`${name} contains an invalid IP/CIDR: ${entry}`);
    }
    return entry;
  }))];
}

export function normalizeIPPolicy(input) {
  return {
    enabled: input?.enabled === true,
    deny: normalizeList(input?.deny ?? [], "deny list"),
    allow: normalizeList(input?.allow ?? [], "allow list")
  };
}

export function renderIPPolicy(input, globalEnabled = true) {
  const policy = normalizeIPPolicy(input);
  const lines = ["# Generated by WAF Lab Portal. Client IP is set by the trusted pre-Coraza handler."];
  if (!globalEnabled || !policy.enabled) return `${lines.join("\n")}\n`;
  if (policy.deny.length) {
    lines.push(`SecRule REQUEST_HEADERS:X-Lab-Client-IP "@ipMatch ${policy.deny.join(",")}" "id:100030,phase:1,deny,status:403,log,msg:'WAF lab IP denylist',logdata:'client=%{REQUEST_HEADERS.X-Lab-Client-IP} country=%{REQUEST_HEADERS.X-Lab-Country} source=%{REQUEST_HEADERS.X-Lab-Geo-Source}'"`);
  }
  if (policy.allow.length) {
    lines.push(`SecRule REQUEST_HEADERS:X-Lab-Client-IP "!@ipMatch ${policy.allow.join(",")}" "id:100031,phase:1,deny,status:403,log,msg:'WAF lab IP outside allowlist',logdata:'client=%{REQUEST_HEADERS.X-Lab-Client-IP} country=%{REQUEST_HEADERS.X-Lab-Country} source=%{REQUEST_HEADERS.X-Lab-Geo-Source}'"`);
  }
  return `${lines.join("\n")}\n`;
}
