const METHODS = new Set(["GET", "POST", "PUT", "PATCH", "DELETE"]);
const PATH = /^\/[A-Za-z0-9/_ .-]{0,119}$/;
const TARGET = /^(ARGS|ARGS_GET|ARGS_POST|REQUEST_HEADERS|REQUEST_COOKIES):[A-Za-z0-9_.-]{1,64}$/;

export function normalizeTuning(input, now = new Date(), existingIds = new Set()) {
  if (!Array.isArray(input) || input.length > 40) throw new Error("tuning_rules must contain at most 40 entries");
  const ids = new Set();
  return input.map((raw) => {
    const id = String(raw.id || "");
    const ruleId = Number(raw.rule_id);
    const site = String(raw.site || "finance-vulnerable");
    const path = String(raw.path || "");
    const method = String(raw.method || "").toUpperCase();
    const scope = String(raw.scope || "target");
    const target = String(raw.target || "");
    const reason = String(raw.reason || "").trim();
    const expires = new Date(raw.expires_at);
    if (!/^[a-f0-9-]{36}$/.test(id) || ids.has(id)) throw new Error("invalid or duplicate tuning ID");
    ids.add(id);
    if (!Number.isInteger(ruleId) || ruleId < 900000 || ruleId > 999999) throw new Error("tuning supports CRS rule IDs 900000–999999");
    if (!["finance-vulnerable", "finance-patched"].includes(site)) throw new Error("invalid finance site");
    if (!PATH.test(path) || path === "/" || path.includes("..") || path.includes("//") || path.includes(" ")) throw new Error("tuning path must be an exact safe non-root path");
    if (!METHODS.has(method)) throw new Error("invalid tuning method");
    if (!["target", "rule"].includes(scope)) throw new Error("invalid tuning scope");
    if (scope === "target" && !TARGET.test(target)) throw new Error("target must be a specific ARGS or request header/cookie field");
    if (scope === "rule" && target) throw new Error("whole-rule exclusion cannot have a target");
    if (reason.length < 5 || reason.length > 200) throw new Error("tuning reason must be 5–200 characters");
    if (!Number.isFinite(expires.getTime()) || expires.getTime() > now.getTime() + 30 * 86400000) throw new Error("tuning expiry must be within 30 days");
    if (expires <= now && !existingIds.has(id)) throw new Error("new tuning expiry must be in the future");
    return { id, rule_id: ruleId, site, path, method, scope, target: scope === "target" ? target : "", reason, expires_at: expires.toISOString(), enabled: raw.enabled !== false, source: raw.source === "automatic" ? "automatic" : "manual" };
  });
}

export function renderTuning(rules, now = new Date()) {
  const lines = ["# Generated by WAF Lab Portal. Do not edit while the portal runs."];
  let index = 0;
  for (const item of rules) {
    if (!item.enabled || new Date(item.expires_at) <= now) continue;
    const action = item.scope === "target"
      ? `ctl:ruleRemoveTargetById=${item.rule_id};${item.target}`
      : `ctl:ruleRemoveById=${item.rule_id}`;
    const expires = Math.floor(new Date(item.expires_at).getTime() / 1000);
    // Tuning is bound to one exact lab Host value. Avoid a regex here: a
    // malformed or unexpectedly interpreted host expression could make an
    // exception for one origin affect the other origin.
    const host = item.site === "finance-patched" ? "patched.localhost" : "localhost";
    lines.push(`SecRule REQUEST_FILENAME "@streq ${item.path}" "id:${110000 + index},phase:1,pass,nolog,t:none,chain"`);
    lines.push(`SecRule REQUEST_METHOD "@streq ${item.method}" "t:none,chain"`);
    lines.push(`SecRule REQUEST_HEADERS:Host "@streq ${host}" "t:none,t:lowercase,chain"`);
    // ctl is non-disruptive and runs as soon as its own rule matches. Keep it
    // on the final chain member so path/method/host/expiry all gate the action.
    lines.push(`SecRule TIME_EPOCH "@lt ${expires}" "t:none,${action}"`);
    index++;
  }
  return `${lines.join("\n")}\n`;
}
